name: order_tests
description: Order tests.
version: 0.0.4
homepage: https://github.com/edufolly/order_tests

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  # https://pub.dev/packages/args
  args: ^2.5.0

  # https://pub.dev/packages/http
  http: ^1.2.2

  # https://pub.dev/packages/path
  path: ^1.9.0

dev_dependencies:
  # https://pub.dev/packages/lints
  flutter_lints: ^4.0.0

  # https://pub.dev/packages/test
  test: ^1.25.8
