name: order_tests
description: A sample command-line application.
version: 0.0.1
homepage: https://github.com/edufolly/order_tests

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.0
