name: order_tests
description: A sample command-line application.
version: 0.0.1
homepage: https://github.com/edufolly/order_tests

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # https://pub.dev/packages/path
  path: ^1.9.0

dev_dependencies:

  # https://pub.dev/packages/lints
  flutter_lints: ^3.0.0

  # https://pub.dev/packages/test
  test: ^1.25.2
