name: order_tests
description: Order tests.
version: 0.0.3
homepage: https://github.com/edufolly/order_tests

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # https://pub.dev/packages/args
  args: ^2.5.0

  # https://pub.dev/packages/http
  http: ^1.2.0

  # https://pub.dev/packages/path
  path: ^1.9.0

dev_dependencies:

  # https://pub.dev/packages/lints
  flutter_lints: ^3.0.0

  # https://pub.dev/packages/test
  test: ^1.25.4
